Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
  ### Jenkins Server  ####
    config.vm.define "jenkinserver" do |jenkinserver|
      jenkinserver.vm.box = "geerlingguy/ubuntu2004"
      jenkinserver.vm.hostname = "jenkinserver"
      jenkinserver.vm.network "private_network", ip: "192.168.25.11"
      jenkinserver.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
      jenkinserver.vm.provision "shell", path: "jenkins-setup.sh"  
    end

  ### Gitlab Server ####
    config.vm.define "gitlabserver" do |gitlabserver|
        gitlabserver.vm.box = "geerlingguy/ubuntu2004"
        gitlabserver.vm.hostname = "gitlabserver"
        gitlabserver.vm.network "private_network", ip: "192.168.25.12"
        gitlabserver.vm.provider "virtualbox" do |vb|
         vb.memory = "8000"
        end
    end
  
  ### Database Server ####
    config.vm.define "db" do |db|
      db.vm.box = "geerlingguy/ubuntu2004"
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.25.13"
      db.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
    end
  
  ### Development Server ####
    config.vm.define "devserver" do |devserver|
      devserver.vm.box = "geerlingguy/ubuntu2004"
      devserver.vm.hostname = "devserver"
      devserver.vm.network "private_network", ip: "192.168.25.14"
      devserver.vm.provider "virtualbox" do |vb|
       vb.memory = "8000"
      end
    end

  ### Build Server ####
    config.vm.define "buildserver" do |buildserver|
      buildserver.vm.box = "geerlingguy/ubuntu2004"
      buildserver.vm.hostname = "buildserver"
      buildserver.vm.network "private_network", ip: "192.168.25.15"
      buildserver.vm.provider "virtualbox" do |vb|
       vb.memory = "8000"
      end
    end

    ### Artifactory Server ####
    config.vm.define "artifactoryserver" do |artifactoryserver|
      artifactoryserver.vm.box = "geerlingguy/ubuntu2004"
      artifactoryserver.vm.hostname = "artifactoryserver"
      artifactoryserver.vm.network "private_network", ip: "192.168.25.16"
      artifactoryserver.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
    end

  end
  