Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
  ### Jenkins Server  ####
    config.vm.define "jenkinserver" do |jenkinserver|
      jenkinserver.vm.box = "geerlingguy/ubuntu2004"
      jenkinserver.vm.hostname = "jenkinserver"
      jenkinserver.vm.network "private_network", ip: "192.168.25.11"
      jenkinserver.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
      jenkinserver.vm.provision "shell", path: "jenkins-setup.sh"  
    end

  ### Gitlab Server ####
    config.vm.define "gitlabserver" do |gitlabserver|
        gitlabserver.vm.box = "geerlingguy/ubuntu2004"
        gitlabserver.vm.hostname = "gitlabserver"
        gitlabserver.vm.network "private_network", ip: "192.168.25.12"
        gitlabserver.vm.provider "virtualbox" do |vb|
         vb.memory = "5000"
        end
    end
  
  ### Database Server ####
    config.vm.define "db" do |db|
      db.vm.box = "geerlingguy/ubuntu2004"
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.25.13"
      db.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
    end
  
  ### Development Server ####
    config.vm.define "devserver" do |devserver|
      devserver.vm.box = "geerlingguy/ubuntu2004"
      devserver.vm.hostname = "devserver"
      devserver.vm.network "private_network", ip: "192.168.25.14"
      devserver.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
    end

  ### Build Server ####
    config.vm.define "buildserver" do |buildserver|
      buildserver.vm.box = "geerlingguy/ubuntu2004"
      buildserver.vm.hostname = "buildserver"
      buildserver.vm.network "private_network", ip: "192.168.25.15"
      buildserver.vm.provider "virtualbox" do |vb|
       vb.memory = "4000"
      end
    end

    ### Artifactory Server ####
    # config.vm.define "artifactoryserver" do |artifactoryserver|
    #   artifactoryserver.vm.box = "geerlingguy/ubuntu2004"
    #   artifactoryserver.vm.hostname = "artifactoryserver"
    #   artifactoryserver.vm.network "private_network", ip: "192.168.25.16"
    #   artifactoryserver.vm.provider "virtualbox" do |vb|
    #    vb.memory = "4000"
    #   end
    # end

    ### K8s Master 1 #### 
    config.vm.define "k8smaster1" do |k8smaster1|
      k8smaster1.vm.box = "bento/ubuntu-24.04"
      k8smaster1.vm.hostname = "k8smaster1"
      k8smaster1.vm.network "private_network", ip: "192.168.25.21"
      k8smaster1.vm.provider "virtualbox" do |vb|
       vb.memory = "8000"
      end
    end

    ### K8s Master 2 ####
    config.vm.define "k8smaster2" do |k8smaster2|
      k8smaster2.vm.box = "bento/ubuntu-24.04"
      k8smaster2.vm.hostname = "k8smaster2"
      k8smaster2.vm.network "private_network", ip: "192.168.25.22"
      k8smaster2.vm.provider "virtualbox" do |vb|
       vb.memory = "6000"
      end
    end

    ### K8s Master 3 ####
    config.vm.define "k8smaster3" do |k8smaster3|
      k8smaster3.vm.box = "bento/ubuntu-24.04"
      k8smaster3.vm.hostname = "k8smaster3"
      k8smaster3.vm.network "private_network", ip: "192.168.25.23"
      k8smaster3.vm.provider "virtualbox" do |vb|
       vb.memory = "6000"
      end
    end

    ### K8s Master 3 ####
    config.vm.define "lbserver" do |lbserver|
      lbserver.vm.box = "bento/ubuntu-24.04"
      lbserver.vm.hostname = "lbserver"
      lbserver.vm.network "private_network", ip: "192.168.25.24"
      lbserver.vm.provider "virtualbox" do |vb|
        vb.memory = "4000"
      end
    end
  end
  
 