apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: online-shop-backend-autoscaler
  namespace: online-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: online-shop-backend
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
